# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b213a2848aab7fa1af50161f8357960a328d6e1d619ce00dd32c86de2b55ddf9c249bdea104ededaa458cea1b5886823a12de8e86bdc18cbd455fb72d81207d4

test:
  secret_key_base: 07aac434a609a37b7d30c3d8786f0eb3370979a9caecc2a6195d457e9c2c8469a2d03b6acad3aeccf73224c0feb5f2d2a242856c1d5b58f2049799633566be0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
